# Generated by Django 6.1 on 2026-08-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_students', models.PositiveIntegerField()),
                ('total_coursework_weightage', models.FloatField()),
                ('average_coursework_performance', models.FloatField()),
                ('weakest_class_chapter', models.CharField(blank=True, max_length=100)),
                ('strongest_class_chapter', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=100)),
                ('class_average', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_summaries', to='analytics_api.analysisupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('analysis', 'assessment_name'), name='unique_assessment_per_analysis')],
            },
        ),
        migrations.CreateModel(
            name='ChapterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('class_average', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_summaries', to='analytics_api.analysisupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('analysis', 'chapter_name'), name='unique_chapter_per_analysis')],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('coursework_performance', models.FloatField()),
                ('predicted_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('generic_features', models.JSONField(default=dict)),
                ('assessment_results', models.JSONField(default=dict)),
                ('chapter_results', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analytics_api.analysisupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('analysis', 'student_id'), name='unique_student_per_analysis')],
            },
        ),
    ]
